export const CLICK_INCREMENT_VALUE = 'CLICK_INCREMENT_VALUE';
export const CLICK_DECREMENT_VALUE = 'CLICK_DECREMENT_VALUE';
export const CLICK_DELETE_VALUE = 'CLICK_DELETE_VALUE';
export const CLICK_INSERT_VALUE = 'CLICK_INSERT_VALUE';
export const CLICK_FILTER_VALUE = 'CLICK_FILTER_VALUE';
export const CLICK_SORT_VALUE = 'CLICK_SORT_VALUE';
export const CLICK_RESET_VALUE = "CLICK_RESET_VALUE";
export const CLICK_PAGINATE = 'CLICK_PAGINATE';